const screens=[...document.querySelectorAll('[data-screen]')];
const routeLinks=[...document.querySelectorAll('a[href^="#/"]')];
const marketData={
 famous:{cta:'PUT MY REPUTATION ON IT',stakes:['MEH','GOSSIP','I HEARD THINGS','SOURCE: TRUST ME','I KNOW THEM PERSONALLY'],mobLow:'The mob is pretending to be reasonable.',mobNear:'Disturbingly unanimous.',mobHigh:'Apparently everyone has the same terrible source.',eyebrow:'FAMOUS PEOPLE',game:"SHORT 'EM",deck:"Who's going up? Who's going down? Put your DoomBucks where your judgment probably shouldn't be.",question:'Will this celebrity couple publicly announce a separation before August 31?',art:'RINGS',caption:'LOVE, LEVERAGED',opening:31,current:46,calls:187,movement:'+15',mob:'46%',you:'67%'},
 entertainment:{cta:'COMMIT TO THE REVIEW',stakes:['MATINEE','OPENING NIGHT','I BOUGHT POPCORN','CRITICS ARE COWARDS','PUT IT ON THE POSTER'],mobLow:'The audience has not found its seats yet.',mobNear:'Critics and civilians are alarmingly aligned.',mobHigh:'The hype machine has achieved sentience.',eyebrow:'ENTERTAINMENT',game:'HIT / FLOP / CHAOS',deck:'Hits, bombs, and cultural train wrecks. Pick the ending before everyone rewrites history.',question:'Will this hyped release land as a HIT, FLOP, or CHAOS event?',art:'REEL',caption:'OPENING NIGHT',opening:42,current:39,calls:264,movement:'−3',mob:'39%',you:'67%'},
 internet:{cta:'BET ON THE BRAIN ROT',stakes:['SCROLLED PAST','SENT TO ONE FRIEND','GROUP CHAT INFECTED','MY AUNT POSTED IT','TERMINALLY ONLINE'],mobLow:'The internet has not ruined this yet.',mobNear:'The hive mind agrees. That seems healthy.',mobHigh:'The algorithm has chosen its sacrifice.',eyebrow:'INTERNET',game:'PEAK MEME',deck:'Catch it before your aunt sends it to you.',question:'Where will this meme be in its lifecycle by next Friday?',art:'PHONE',caption:'BRAIN ROT INDEX',opening:37,current:53,calls:318,movement:'+16',mob:'53%',you:'67%'},
 trends:{cta:'BUY INTO THE DELUSION',stakes:['WINDOW SHOPPING','ADD TO CART','INFLUENCED','MAXIMUM FOMO','I AM THE BUBBLE'],mobLow:'The mob has not discovered its credit card yet.',mobNear:'Everyone wants the same stupid thing.',mobHigh:'Congratulations. Consumerism is winning.',eyebrow:'TRENDS',game:'BUY THE BUBBLE',deck:'Buy the ridiculous thing early. Cash out before everyone owns one.',question:'How far will this product craze spread before the bubble pops?',art:'BAG',caption:'BUY HIGHER?',opening:26,current:41,calls:221,movement:'+15',mob:'41%',you:'67%'},
 wtf:{cta:"MAKE IT EVERYONE'S PROBLEM",stakes:['SURE, WHY NOT','THIS SEEMS BAD',"I'M LISTENING",'RELEASE THE IDIOTS',"I'LL DIE ON THIS HILL"],mobLow:'Reality is still warming up.',mobNear:'One of you has lost the plot. Possibly both.',mobHigh:'Apparently everyone knows something horrible now.',eyebrow:'WTF?!',game:'TOO WEIRD TO FAIL',deck:'How far into absurdity are you willing to follow reality?',question:'Will this bizarre story escalate all the way to celebrity involvement?',art:'EYE',caption:'ABSURDITY FUTURES',opening:12,current:18,calls:143,movement:'+6',mob:'18%',you:'67%'}
};

function beliefCopy(d, player){const gap=Math.abs(player-d.current);if(gap<=8)return d.mobNear;if(d.current>=50)return d.mobHigh;return d.mobLow;}
function updateCategoryLanguage(d){
 const cta=document.getElementById('makeCallButton'); if(cta) cta.textContent=d.cta;
 const probabilityInput=document.getElementById('probabilityRange');
 const playerProbability=probabilityInput ? +probabilityInput.value : 67;
 const mob=document.getElementById('mobMicrocopy'); if(mob) mob.textContent=beliefCopy(d,playerProbability);
 document.querySelectorAll('.stake-group button').forEach((button,i)=>{
   const label=d.stakes[i];
   const labelNode=button.querySelector('.stake-label');
   if(labelNode && label) labelNode.textContent=label;
 });
}
const roasts=['Congratulations. You played yourself.','Humanity is disappointed in you.','Bold move. No one asked for it.','Your therapist is going to charge extra.','You chose violence today.','Your bad judgment is now permanently documented.','Future you is already drafting the apology.','This is why we can’t have nice things.','Certified clown behavior.','Your instincts called in sick.','The delusion is strong with this one.','You were so close to thinking this through.','This is not the flex you think it is.','We’ve put this in the archives of regret.','Keep telling yourself that.','You really woke up and chose chaos.','Big confidence. Tiny brakes.','Filed under: Things That May Age Poorly.','Hope is not a strategy. Apparently neither is this.','Your judgment has left the building.','Your call has been entered into evidence.','Someone had to make this decision. Unfortunately, it was you.','The market is quietly backing away from you.','You’re the main character. Tragically.','Reality has been notified.'];
const praise=['Well done!','Congratulations!','Your mom must be so proud.','We’re all very proud of you.','Great work, champ.','Excellent decision-making!','Congratulations on believing in yourself.','Look at you, making choices.','We’re putting this one on the fridge.','You should absolutely tell people about this.','Another triumph of the human spirit.','Give yourself a little treat.','Your confidence remains inspiring.','Congratulations on following your heart.','Somebody get this genius a trophy.','You really gave it your all.','That’s the spirit!','We’re sure you know what you’re doing.','Never let good judgment hold you back.','What an achievement.','Your commitment is truly breathtaking.','Take a bow.','Another proud moment for your family.','We’re all rooting for you. From a safe distance.','Congratulations. Nothing could possibly go wrong.'];
let lastRoast=-1,lastPraise=-1;
function pick(pool,last){let i;do{i=Math.floor(Math.random()*pool.length)}while(i===last&&pool.length>1);return [pool[i],i]}
const waiting=[
 {tag:'FAMOUS PEOPLE',q:'Will the apology arrive before the weekend?',call:'YES · 71%',entry:'34%',current:'62%',delta:'+28',by:'Aug 24',mood:'against'},
 {tag:'ENTERTAINMENT',q:'Will the reboot land in CHAOS territory?',call:'CHAOS · 58%',entry:'21%',current:'29%',delta:'+8',by:'Aug 31',mood:'with'},
 {tag:'INTERNET',q:'Will this meme be DEAD by Friday?',call:'DEAD · 74%',entry:'15%',current:'38%',delta:'+23',by:'Aug 21',mood:'against'},
 {tag:'TRENDS',q:'Will everyone suddenly own this stupid little object?',call:'HOLD',entry:'HOT',current:'EVERYWHERE',delta:'↑',by:'Aug 29',mood:'against'}];
const leaders=[['#1','@CultureVulture','+8,420'],['#2','@BadDecision69','+7,915'],['#3','@Nostradumbass','+7,610'],['#4','@TrendUndertaker','+6,880'],['#5','@MemeCoroner','+6,540'],['#126','@DoomScrollDaddy','+1,355'],['#127','YOU','+1,340']];
document.getElementById('waitingGrid').innerHTML=waiting.map(x=>`<article class="waiting-card ${x.mood}"><div class="tag">${x.tag}</div><h2>${x.q}</h2><div class="movement-alert">YOU ENTERED ${x.entry} → THE MOB IS NOW ${x.current} <b>${x.delta}</b></div><div class="waiting-stats"><div><span>YOUR CALL</span><strong>${x.call}</strong></div><div><span>ENTRY</span><strong>${x.entry}</strong></div><div><span>CURRENT</span><strong>${x.current}</strong></div><div><span>RESOLVE BY</span><strong>${x.by}</strong></div></div><p class="waiting-snark">${x.mood==='against'?'Well, this got awkward.':'For once, the mob is enabling you.'}</p></article>`).join('');
document.getElementById('leaderboardList').innerHTML=leaders.map(x=>`<li class="${x[1]==='YOU'?'you':''}"><span class="rank-num">${x[0]}</span><span>${x[1]}</span><span class="rank-score">${x[2]} DB</span></li>`).join('');
function route(){const name=(location.hash.split('/')[1]||'today').split('?')[0];const valid=['today','waiting','leaderboard','profile'].includes(name)?name:'today';screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===valid));routeLinks.forEach(a=>a.setAttribute('aria-current',a.getAttribute('href')===`#/${valid}`?'page':'false'));document.getElementById('main').focus({preventScroll:true})}
window.addEventListener('hashchange',route);route();
const chips=[...document.querySelectorAll('.category-chip')];let currentCategory=0;function activateCategory(i){currentCategory=(i+chips.length)%chips.length;const chip=chips[currentCategory];chips.forEach(c=>c.classList.remove('active'));chip.classList.add('active');const d=marketData[chip.dataset.category];document.body.dataset.category=chip.dataset.category;document.getElementById('categoryEyebrow').textContent=d.eyebrow;document.getElementById('gameName').textContent=d.game;document.getElementById('categoryDeck').textContent=d.deck;document.getElementById('marketQuestion').textContent=d.question;document.getElementById('artSymbol').textContent=d.art;document.querySelector('.art-caption').textContent=d.caption;document.getElementById('openingOdds').textContent=d.opening+'%';document.getElementById('currentOdds').textContent=d.current+'%';document.getElementById('mobOdds').textContent=d.current+'%';document.getElementById('callCount').textContent=d.calls;document.getElementById('marketNumber').textContent=`MARKET 0${currentCategory+1} OF 05`;document.getElementById('progressLabel').textContent=`${currentCategory+1} / 5 CALLS`;document.getElementById('progressFill').style.width=`${(currentCategory+1)*20}%`;document.getElementById('movementNumber').innerHTML=`${d.opening}% <span>→</span> ${d.current}%`;
updateCategoryLanguage(d);}
chips.forEach((c,i)=>c.addEventListener('click',()=>activateCategory(i)));document.getElementById('prevMarket').addEventListener('click',()=>activateCategory(currentCategory-1));document.getElementById('nextMarket').addEventListener('click',()=>activateCategory(currentCategory+1));activateCategory(0);
const range=document.getElementById('probabilityRange'),value=document.getElementById('probabilityValue');function setProb(n){range.value=Math.max(1,Math.min(99,n));value.textContent=range.value+'%';document.getElementById('youOdds').textContent=range.value+'%';const d=marketData[chips[currentCategory].dataset.category];const mob=document.getElementById('mobMicrocopy');if(mob)mob.textContent=beliefCopy(d,+range.value)}range.addEventListener('input',()=>setProb(+range.value));document.getElementById('probDown').addEventListener('click',()=>setProb(+range.value-1));document.getElementById('probUp').addEventListener('click',()=>setProb(+range.value+1));
let stake=500,choice='BUY';[...document.querySelectorAll('.stake-group button')].forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.stake-group button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');stake=+b.dataset.stake;document.getElementById('winAmount').textContent=`+${stake.toLocaleString()} DB`;document.getElementById('loseAmount').textContent=`−${stake.toLocaleString()} DB`;document.getElementById('riskRemaining').textContent=`Today's risk left after this call: ${Math.max(0,1000-stake).toLocaleString()} DB`;}));[...document.querySelectorAll('.choice-button')].forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.choice-button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');choice=b.dataset.choice.toUpperCase()}));
document.getElementById('resolutionButton').addEventListener('click',()=>document.getElementById('resolutionDialog').showModal());
document.getElementById('makeCallButton').addEventListener('click',()=>{const btn=document.getElementById('makeCallButton');btn.classList.add('slammed');setTimeout(()=>btn.classList.remove('slammed'),450);let r,p;[r,lastRoast]=pick(roasts,lastRoast);[p,lastPraise]=pick(praise,lastPraise);document.getElementById('callRoast').textContent=r;document.getElementById('callPraise').textContent=p;document.getElementById('callSummary').textContent=`${choice} · ${range.value}% confidence · ${stake.toLocaleString()} DoomBucks`;setTimeout(()=>document.getElementById('callDialog').showModal(),180)});
document.querySelectorAll('.leader-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.leader-tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
if('serviceWorker' in navigator){navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
